[project]
name = "string-case-translator"
version = "1.0.3"
description = "A DevTool for converting strings in different cases"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "bfich-guy", email = "bfich-guy@example.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"